# Generated by Django 5.0.6 on 2024-09-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trip_dailyexpense_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
