# Generated by Django 5.0.6 on 2024-09-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_trip_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Distance (KM)'),
        ),
    ]
