# Generated by Django 5.0.6 on 2024-11-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_paymenttransaction_comment_alter_trip_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmode',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('PKR', 'Pakistani Rupee'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='PKR', max_length=3),
        ),
    ]
