# Generated by Django 5.0.6 on 2024-11-02 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('primary_color', models.CharField(help_text='Hex color code (e.g., #2196F3)', max_length=7)),
                ('secondary_color', models.CharField(help_text='Hex color code (e.g., #FF5722)', max_length=7)),
                ('accent_color', models.CharField(blank=True, help_text='Hex color code for accent color (e.g., #FFC107)', max_length=7)),
                ('background_color', models.CharField(blank=True, help_text='Hex color code for background color (e.g., #FFFFFF)', max_length=7)),
                ('error_color', models.CharField(blank=True, help_text='Hex color code for error color (e.g., #F44336)', max_length=7)),
                ('surface_color', models.CharField(blank=True, help_text='Hex color code for surface color (e.g., #FFFFFF)', max_length=7)),
                ('on_primary_color', models.CharField(blank=True, help_text='Hex color code for text on primary color (e.g., #FFFFFF)', max_length=7)),
                ('on_secondary_color', models.CharField(blank=True, help_text='Hex color code for text on secondary color (e.g., #000000)', max_length=7)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
