from django.core.management.base import BaseCommand
from apps.theme.models import Theme

class Command(BaseCommand):
    help = 'Add popular Material Design theme colors to the database'

    def handle(self, *args, **kwargs):
        themes = [
            {
                'name': 'Deep Purple',
                'primary_color': '#673AB7',
                'secondary_color': '#FF4081',
                'accent_color': '#FF4081',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#FFFFFF',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Indigo',
                'primary_color': '#3F51B5',
                'secondary_color': '#FF4081',
                'accent_color': '#FF4081',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#FFFFFF',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Pink',
                'primary_color': '#E91E63',
                'secondary_color': '#F50057',
                'accent_color': '#F50057',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#FFFFFF',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Red',
                'primary_color': '#F44336',
                'secondary_color': '#FF5252',
                'accent_color': '#FF5252',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#FFFFFF',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Orange',
                'primary_color': '#FF9800',
                'secondary_color': '#FF5722',
                'accent_color': '#FF5722',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#FFFFFF',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Amber',
                'primary_color': '#FFC107',
                'secondary_color': '#FF9800',
                'accent_color': '#FF9800',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#000000',
                'on_secondary_color': '#FFFFFF',
            },
            {
                'name': 'Yellow',
                'primary_color': '#FFEB3B',
                'secondary_color': '#FFD600',
                'accent_color': '#FFD600',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#000000',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Lime',
                'primary_color': '#CDDC39',
                'secondary_color': '#A4D600',
                'accent_color': '#A4D600',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#000000',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Green',
                'primary_color': '#4CAF50',
                'secondary_color': '#69F0AE',
                'accent_color': '#69F0AE',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#FFFFFF',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Teal',
                'primary_color': '#009688',
                'secondary_color': '#A7FFEB',
                'accent_color': '#A7FFEB',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#FFFFFF',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Blue',
                'primary_color': '#2196F3',
                'secondary_color': '#40C4FF',
                'accent_color': '#40C4FF',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#FFFFFF',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Light Blue',
                'primary_color': '#03A9F4',
                'secondary_color': '#00B0FF',
                'accent_color': '#00B0FF',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#FFFFFF',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Cyan',
                'primary_color': '#00BCD4',
                'secondary_color': '#18FFFF',
                'accent_color': '#18FFFF',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#FFFFFF',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Light Green',
                'primary_color': '#8BC34A',
                'secondary_color': '#B2FF59',
                'accent_color': '#B2FF59',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#FFFFFF',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Dark Green',
                'primary_color': '#388E3C',
                'secondary_color': '#4CAF50',
                'accent_color': '#4CAF50',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#FFFFFF',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Brown',
                'primary_color': '#795548',
                'secondary_color': '#A95D4C',
                'accent_color': '#A95D4C',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#FFFFFF',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Grey',
                'primary_color': '#9E9E9E',
                'secondary_color': '#B0BEC5',
                'accent_color': '#B0BEC5',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#000000',
                'on_secondary_color': '#000000',
            },
            {
                'name': 'Blue Grey',
                'primary_color': '#607D8B',
                'secondary_color': '#78909C',
                'accent_color': '#78909C',
                'background_color': '#F5F5F5',
                'error_color': '#F44336',
                'surface_color': '#FFFFFF',
                'on_primary_color': '#FFFFFF',
                'on_secondary_color': '#000000',
            },
        ]

        for theme_data in themes:
            theme, created = Theme.objects.get_or_create(**theme_data)
            if created:
                self.stdout.write(self.style.SUCCESS(f'Theme "{theme.name}" created successfully.'))
            else:
                self.stdout.write(self.style.WARNING(f'Theme "{theme.name}" already exists.'))
